version: '2'
services:
  app:
    volumes:
        - uwsgi:/tmp/uwsgi
        - ./app:/app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME
      - FLASK_DEBUG=1
    command: ./migrate_and_run_dev.sh

  beat_worker:
    volumes:
      - ./app:/app
    build: ./app
    command: watchmedo auto-restart -d . -R -p '*.py' -- celery -A autoapp --loglevel=DEBUG worker -E -B --scheduler Scheduler -s /var/run/celery-beat
    depends_on:
      - db
      - queue
      - cache
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME
      - FLASK_DEBUG=1

  worker:
    volumes:
        - ./app:/app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME
      - FLASK_DEBUG=1
    command: watchmedo auto-restart -d . -R -p '*.py' -- celery -A autoapp --loglevel=DEBUG worker -E
