version: '2'
services:
  app:
    build: ./app
    volumes:
        - uwsgi:/tmp/uwsgi
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME
    depends_on:
      - db
      - queue

  webserver:
    build: ./webserver
    volumes_from:
        - app:rw
    ports:
        - '8080:80'
    depends_on:
      - app
    volumes:
      - uwsgi:/tmp/uwsgi

  db:
    build: ./db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/league/db

  queue:
    image: rabbitmq:3.6.12

  cache:
    image: redis:3.2.11-alpine

  worker_1:
    build: ./app
    command: celery -A autoapp worker -l DEBUG
    depends_on:
      - db
      - queue
      - cache
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME

  worker_2:
    build: ./app
    command: celery -A autoapp worker -l DEBUG
    depends_on:
      - db
      - queue
      - cache
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LEAGUE_ROOT_PASS
      - SLACK_CHANNEL
      - SLACK_WEBHOOK
      - SERVER_NAME

  queue_monitor:
    environment:
      - CELERY_BROKER_URL
    image: mher/flower
    depends_on:
      - queue
      - cache
    ports:
      - '5555:5555'

volumes:
    uwsgi:
    db_data:
